name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Package application
      run: zip -r app.zip . # Package the application

    - name: Create a GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: "Release ${{ github.ref_name }}"
        body: "Automated release for ${{ github.ref_name }}"
